### ISSUE TITLE
See Entity records

### ISSUE THREAD

**Issue by matthew-white** [getodk/central#381]
See the story in the [release criteria](https://docs.google.com/document/d/1qQ7uaAL_hu-HQtsZo2eWrV1jeBFuLB6i1l1w--194kw/edit#bookmark=id.n7ee9272pgmn).

**Comment by dbemke** [comment]
In Data tab the newest entry is at the bottom with nr 1, so each time the user approves an entity it is nr 1 on the list - previous entities numbers are changed e.g nr 1 becomes nr 2. In submissions tab the newest submission is at the top with the highest number so adding a submission doesn't change the number next to the previous submissions.

![Image](https://user-images.githubusercontent.com/56479916/221537866-feb67fe1-0cbf-4bff-af95-0f4fdc63e080.png)

**Comment by matthew-white** [comment]
@dbemke, this should be resolved now (I think @ktuite has updated this behavior). The entities table should behave similarly to the submissions table in this way.

**Comment by dbemke** [comment]
I checked today and the issue is still present (newest entity is nr 1). I checked on

![Image](https://user-images.githubusercontent.com/56479916/221829461-3743a78a-dd4f-4857-adc8-0f8a0ad23afb.png)

**Comment by dbemke** [comment]
**Tested with success!**
